DATABASE:
  URL: postgresql://postgres:2QU8jOkHyZFYVT7eRGLN@containers-us-west-17.railway.app:7126/railway
  PGDATABASE: railway
  PGHOST: containers-us-west-17.railway.app
  PGPASSWORD: 2QU8jOkHyZFYVT7eRGLN
  PGPORT: 7126
  PGUSER: postgres
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE.PGHOST}:${DATABASE.PGPORT}/${DATABASE.PGDATABASE}
    username: ${DATABASE.PGUSER}
    password: ${DATABASE.PGPASSWORD}
    name: document-test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
