spring:
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE.URL}
    username: ${DATABASE.PGUSER}
    password: ${DATABASE.PGPASSWORD}
    name: document-test
DATABASE:
  URL: jdbc:postgresql://postgres:2QU8jOkHyZFYVT7eRGLN@containers-us-west-17.railway.app:7126/railway
  PGDATABASE: railway
  PGHOST: containers-us-west-17.railway.app
  PGPASSWORD: 2QU8jOkHyZFYVT7eRGLN
  PGPORT: 7126
  PGUSER: postgres
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/b26jpa?currentSchema=instagram
    username: postgres
    password: 1234

